name: Weekly Caleb Stats Refresh

on:
  schedule:
    - cron: "0 8 * * 2"   # Runs every Tuesday at 08:00 UTC (Midnight PT)
  workflow_dispatch:      # allows manual run from GitHub Actions tab

jobs:
  refresh-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render refresh endpoint
        run: |
          curl -s https://journey-to-4000.onrender.com/api/refresh
